version: '3'

services:
  db:
    image: postgres:14
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "8432:5432"
    volumes:
      - ./volumes/dbdata:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres





